spring:
  application:
    name: procedure-service

  cloud:
    config:
      uri: http://config-server:8888     # <-- Config Server URI added here
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://eureka-server:27017/procedure_db}
      database: ${SPRING_DATA_MONGODB_DATABASE:procedure_db}

server:
  port: 8085

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.glowkart.procedure: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

async:
  core-pool-size: 5
  max-pool-size: 20
  queue-capacity: 50

services:
  admin:
    base-url: ${ADMIN_SERVICE_BASE_URL:http://admin-service}  # Can use Eureka name

notification:
  default-from-email: ${NOTIFICATION_FROM_EMAIL:no-reply@glowkart.com}
#//For Feign + Eureka, you don’t need the full URL in base-url. You can use the Eureka service name like http://admin-service.